# Generated by Django 3.0 on 2023-10-31 13:51

from django.apps import apps as global_apps
from django.db import migrations


def copy_profile_data(apps, schema_editor):
    try:
        OldModel = apps.get_model("oc_lettings_site", "Profile")
    except LookupError:
        return
    
    NewModel = apps.get_model("profiles", "Profile")
    UserModel = apps.get_model("auth", "User")
    
    NewModel.objects.bulk_create(
        NewModel(user=UserModel.objects.get(id=old_object.user.id),
                 favorite_city=old_object.favorite_city)
        for old_object in OldModel.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.RunPython(copy_profile_data, migrations.RunPython.noop)
    ]
