# Generated by Django 3.0 on 2023-11-01 10:25

from django.db import migrations


class Migration(migrations.Migration):
    """Amends the plural name of the Address object in the admin interface."""
    dependencies = [
        ('lettings', '0002_auto_20231031_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
