# Generated by Django 3.0 on 2023-10-31 14:04

from django.db import migrations


class Migration(migrations.Migration):
    """Deletion of the old app's models following app refactoring."""
    dependencies = [
        ('oc_lettings_site', '0002_auto_20231031_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
